language: java
jdk:
  - openjdk8

branches:
  only:
    - master

#p.326 Travis CI .travis.yml 설정 후 build 이슈
#./gradlew: Permission denied git에 permission을 업데이트 해줘야 travis가 실행할 수 있다.
before_install:
  - chmod +x gradlew

# Travis CI 서버의 HOME
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - jj0101065@gmail.com